name: Auto Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Render
        run: curl -X POST https://api.render.com/deploy/srv-d0u9a46mcj7s739f2alg?key=JEIIlDmCmMI
